In [2]:
import pandas as pd

In [2]:
writer = pd.ExcelWriter('Multiple_year_stock_data_.5PerCSample.xlsx', engine='xlsxwriter')
for i in range(2012,2017,1):
    df=pd.read_excel('Multiple_year_stock_data.xlsx', sheetname=str(i))
    print(df.shape)
    df= df.sample(round(df.shape[0]*.0025))
    df.to_excel(writer, sheet_name=str(i))
    #data_d[i]=df
    print(df.shape)
writer.save()

(566033, 7)
(1415, 7)
(636026, 7)
(1590, 7)
(705713, 7)
(1764, 7)
(760191, 7)
(1900, 7)
(797710, 7)
(1994, 7)

In [8]:
writer = pd.ExcelWriter('Multiple_year_stock_data_3PerCSample.xlsx', engine='xlsxwriter')
for i in range(2012,2017,1):
    df=pd.read_excel('Multiple_year_stock_data.xlsx', sheetname=str(i))
    print(df.shape)
    
    ####
    StockSet = df.sort_values('<ticker>')['<ticker>'].tolist()
    NumStocks=len(set(StockSet))
    NumStocks=round(1.5/100*NumStocks)
    stock_list=[stock for stock in StockSet]
    stocks=random.sample(stock_list, NumStocks)
    df=df[df['<ticker>'].isin(stocks)]
    
    ####
    df.to_excel(writer, index=False, sheet_name=str(i))
    #data_d[i]=df
    print(df.shape)
    print(df.head)
    
    print('----')
writer.save()

(566033, 7)
(9010, 7)
<bound method NDFrame.head of        <ticker>    <date>   <open>   <high>    <low>  <close>    <vol>
1040        AAT  20120102  20.5100  20.5100  20.5100  20.5100        0
1041        AAT  20120103  20.6600  21.1000  20.6500  20.9200   103600
1042        AAT  20120104  20.7600  21.0200  20.2400  20.2500    93600
1043        AAT  20120105  19.9800  20.6200  19.9800  20.4900    89400
1044        AAT  20120106  20.4400  20.6200  20.3500  20.3700    94500
1045        AAT  20120109  20.2800  20.3800  19.7900  19.9200    89300
1046        AAT  20120110  20.1000  20.6400  20.1000  20.3000    79900
1047        AAT  20120111  20.0700  20.7400  20.0700  20.7300    51600
1048        AAT  20120112  20.8000  20.8000  20.0900  20.4300   142900
1049        AAT  20120113  20.2300  20.7100  20.2000  20.6900    87800
1050        AAT  20120116  20.6900  20.6900  20.6900  20.6900        0
1051        AAT  20120117  20.7700  20.9200  20.5500  20.6800   106400
1052        AAT  20120118  20.7200  21.2300  20.7100  21.2200    78700
1053        AAT  20120119  21.2400  21.5000  21.0500  21.2300    93400
1054        AAT  20120120  21.2600  21.4600  21.1500  21.2500    98800
1055        AAT  20120123  21.3800  21.6400  21.1800  21.4600    61900
1056        AAT  20120124  21.3900  21.6300  21.3100  21.4700   176300
1057        AAT  20120125  21.4200  21.4400  21.2800  21.3700   135800
1058        AAT  20120126  21.5100  21.9700  21.3600  21.9300    83300
1059        AAT  20120127  21.7900  22.3000  21.7900  22.0700   123600
1060        AAT  20120130  21.8900  22.1400  21.7000  21.9600   146200
1061        AAT  20120131  21.9500  22.2800  21.5500  22.1400   141900
1062        AAT  20120201  22.2800  22.7100  21.9100  22.6400   167000
1063        AAT  20120202  22.5600  22.6900  22.1900  22.5600   169400
1064        AAT  20120203  22.8200  23.1200  22.4900  23.1100   188600
1065        AAT  20120206  22.8400  23.0100  22.5500  22.7000   104800
1066        AAT  20120207  22.7100  23.1100  22.6300  22.8100    95400
1067        AAT  20120208  22.8700  22.9800  22.4300  22.6600   119000
1068        AAT  20120209  22.6600  22.7000  22.1900  22.2300   105900
1069        AAT  20120210  22.0000  22.2900  21.7800  22.0500    62200
...         ...       ...      ...      ...      ...      ...      ...
530525        V  20121120  36.3850  36.8450  36.2900  36.5850  2391500
530526        V  20121121  36.5550  36.7250  36.4350  36.6650  1641500
530527        V  20121122  36.6650  36.6650  36.6650  36.6650        0
530528        V  20121123  36.8250  37.0300  36.6000  37.0300  1113500
530529        V  20121126  36.9025  36.9025  36.6050  36.8125  2155800
530530        V  20121127  36.7800  36.9600  36.5825  36.6950  2495400
530531        V  20121128  36.5075  36.8375  36.4725  36.8225  2589500
530532        V  20121129  36.9825  37.0825  36.8100  37.0450  3143100
530533        V  20121130  37.0800  37.4825  37.0025  37.4275  3512200
530534        V  20121203  37.5000  37.6800  37.1100  37.1600  2934400
530535        V  20121204  37.2450  37.3125  36.8000  36.8975  2275200
530536        V  20121205  37.1275  37.1275  36.5250  37.0150  2992700
530537        V  20121206  37.1125  37.2250  36.7650  37.1175  2281100
530538        V  20121207  37.2800  37.3200  36.9475  37.1375  1889200
530539        V  20121210  37.1875  37.3175  37.0675  37.1650  2324000
530540        V  20121211  37.1000  37.5825  37.1000  37.2250  3623100
530541        V  20121212  37.4225  37.4500  36.9575  36.9700  4580000
530542        V  20121213  37.0275  37.2750  36.7225  36.8000  3261100
530543        V  20121214  36.7200  36.9225  36.5625  36.7050  2394700
530544        V  20121217  36.7425  37.2825  36.7250  37.2825  3476200
530545        V  20121218  37.2525  37.8875  37.1750  37.6800  2967700
530546        V  20121219  37.7000  37.7100  37.2875  37.2900  2160000
530547        V  20121220  37.4700  38.1275  37.3300  38.1150  2716700
530548        V  20121221  37.7425  37.9950  37.4900  37.6925  3483100
530549        V  20121224  37.5575  37.9050  37.5575  37.7950   818300
530550        V  20121225  37.7950  37.7950  37.7950  37.7950        0
530551        V  20121226  37.8200  37.8225  37.3000  37.4400  1903500
530552        V  20121227  37.4225  37.6625  36.9750  37.3500  2994400
530553        V  20121228  37.1150  37.4825  37.0625  37.1625  1744300
530554        V  20121231  37.0875  37.9025  37.0875  37.8950  3217400

[9010 rows x 7 columns]>
----
(636026, 7)
(9233, 7)
<bound method NDFrame.head of        <ticker>    <date>  <open>  <high>  <low>  <close>    <vol>
21482       AIT  20130101   42.01   42.01  42.01    42.01        0
21483       AIT  20130102   42.88   44.04  42.62    43.55   367200
21484       AIT  20130103   43.62   43.92  43.37    43.76   233100
21485       AIT  20130104   44.05   44.07  43.75    43.90   104300
21486       AIT  20130107   43.54   43.88  43.34    43.50   113700
21487       AIT  20130108   43.36   43.36  42.50    42.93   197200
21488       AIT  20130109   43.13   43.52  42.93    43.28   123500
21489       AIT  20130110   43.33   43.33  42.02    42.45   249300
21490       AIT  20130111   42.53   42.77  42.14    42.60   249400
21491       AIT  20130114   42.59   42.59  42.33    42.52    77300
21492       AIT  20130115   42.16   42.94  42.15    42.80   110400
21493       AIT  20130116   42.76   43.07  42.54    42.93   149800
21494       AIT  20130117   42.95   43.36  42.95    43.30   186800
21495       AIT  20130118   43.31   43.65  43.31    43.65   154900
21496       AIT  20130121   43.65   43.65  43.65    43.65        0
21497       AIT  20130122   43.65   43.99  43.46    43.98   166000
21498       AIT  20130123   44.00   44.06  43.69    43.71   115000
21499       AIT  20130124   43.69   44.00  43.22    43.69   436600
21500       AIT  20130125   43.90   44.22  43.60    44.00   234100
21501       AIT  20130128   44.15   44.22  43.69    43.81   247700
21502       AIT  20130129   43.50   43.93  43.50    43.84   365500
21503       AIT  20130130   43.80   43.89  43.37    43.68   176100
21504       AIT  20130131   43.72   44.04  43.33    43.96   231500
21505       AIT  20130201   44.19   45.16  43.97    44.85   245700
21506       AIT  20130204   44.48   44.76  44.13    44.22   238300
21507       AIT  20130205   44.46   45.09  44.27    44.87   305400
21508       AIT  20130206   44.43   44.74  44.18    44.34   140700
21509       AIT  20130207   44.37   44.37  43.52    43.88   226100
21510       AIT  20130208   43.98   44.23  43.90    44.22    79400
21511       AIT  20130211   44.13   44.29  43.84    43.98    66400
...         ...       ...     ...     ...    ...      ...      ...
633349      YUM  20131120   74.00   74.00  72.10    72.32  3713900
633350      YUM  20131121   72.44   75.15  72.34    74.92  5691000
633351      YUM  20131122   75.82   78.68  75.79    78.30  8320300
633352      YUM  20131125   77.88   78.37  77.45    78.01  2916700
633353      YUM  20131126   77.40   78.28  77.39    77.65  3254000
633354      YUM  20131127   77.48   77.69  76.88    77.59  2419000
633355      YUM  20131128   77.59   77.59  77.59    77.59        0
633356      YUM  20131129   77.59   78.24  77.36    77.68  1361300
633357      YUM  20131202   77.56   78.57  77.38    77.71  2503600
633358      YUM  20131203   75.40   76.41  74.83    75.61  6714800
633359      YUM  20131204   75.66   76.16  75.40    75.66  2471500
633360      YUM  20131205   75.10   75.29  74.00    74.39  3789700
633361      YUM  20131206   75.25   75.34  74.08    74.37  2890700
633362      YUM  20131209   74.37   74.72  74.17    74.30  2788100
633363      YUM  20131210   74.30   74.30  73.24    73.41  2486100
633364      YUM  20131211   73.59   74.02  72.76    72.90  1912400
633365      YUM  20131212   72.63   72.89  71.50    71.60  2957300
633366      YUM  20131213   71.74   72.65  71.63    71.81  2225400
633367      YUM  20131216   73.17   73.89  72.70    73.23  2958900
633368      YUM  20131217   73.07   73.19  71.75    71.87  2470200
633369      YUM  20131218   71.87   72.74  71.25    72.73  2599400
633370      YUM  20131219   72.48   72.93  71.78    72.75  2697700
633371      YUM  20131220   72.85   73.79  72.77    73.39  3100300
633372      YUM  20131223   73.50   74.00  72.81    73.97  1827600
633373      YUM  20131224   73.96   74.19  73.63    74.10   708100
633374      YUM  20131225   74.10   74.10  74.10    74.10        0
633375      YUM  20131226   74.12   74.40  73.92    74.11   812500
633376      YUM  20131227   74.41   74.41  73.56    73.87   872300
633377      YUM  20131230   73.85   74.97  73.84    74.92  1953200
633378      YUM  20131231   75.00   76.41  75.00    75.61  2132900

[9233 rows x 7 columns]>
----

(705713, 7)
(10804, 7)
<bound method NDFrame.head of        <ticker>    <date>  <open>  <high>  <low>  <close>    <vol>
11096       AER  20140101   38.35   38.35  38.35    38.35        0
11097       AER  20140102   38.23   38.48  37.19    37.36  2002600
11098       AER  20140103   37.25   37.76  35.64    36.11  2144000
11099       AER  20140106   36.10   36.52  35.51    35.82  1335500
11100       AER  20140107   36.17   36.22  35.40    35.69   962000
11101       AER  20140108   35.68   36.19  35.37    35.83   704900
11102       AER  20140109   35.68   35.92  35.34    35.63   738500
11103       AER  20140110   35.77   36.31  35.41    36.05  1386700
11104       AER  20140113   35.57   36.12  35.49    35.70  1031200
11105       AER  20140114   36.09   36.15  35.26    35.97  1141600
11106       AER  20140115   35.31   36.08  35.31    35.80  1454400
11107       AER  20140116   35.78   36.10  35.16    35.30  1608800
11108       AER  20140117   35.52   36.47  35.37    36.00  1995300
11109       AER  20140120   36.00   36.00  36.00    36.00        0
11110       AER  20140121   35.98   36.26  35.77    36.18  1694500
11111       AER  20140122   35.99   36.49  35.91    36.31  1707200
11112       AER  20140123   36.36   36.40  35.71    35.75  1267500
11113       AER  20140124   35.62   35.82  34.42    34.71  1820000
11114       AER  20140127   34.61   35.83  34.38    35.40  1286500
11115       AER  20140128   35.40   37.16  35.22    37.10  1008700
11116       AER  20140129   37.10   38.55  36.04    38.27  2481000
11117       AER  20140130   38.51   38.82  37.81    37.82  1554100
11118       AER  20140131   37.54   38.02  36.77    37.19  2068700
11119       AER  20140203   37.03   37.16  36.09    36.53   894400
11120       AER  20140204   36.44   38.61  36.44    38.56  1979600
11121       AER  20140205   38.23   38.59  37.60    37.96  1978200
11122       AER  20140206   37.92   39.38  37.57    39.03  2007900
11123       AER  20140207   38.99   39.21  38.23    38.44  1091500
11124       AER  20140210   38.51   38.64  37.86    38.08   604600
11125       AER  20140211   37.95   39.23  37.95    38.85  1329100
...         ...       ...     ...     ...    ...      ...      ...
689187      WOR  20141120   36.53   37.54  36.53    37.44   128100
689188      WOR  20141121   38.35   38.51  37.51    37.73   198900
689189      WOR  20141124   37.76   38.56  37.60    38.38   188000
689190      WOR  20141125   38.25   38.84  38.25    38.57    89400
689191      WOR  20141126   38.72   38.89  38.15    38.48   149800
689192      WOR  20141127   38.48   38.48  38.48    38.48        0
689193      WOR  20141128   38.19   38.35  37.47    37.71   147700
689194      WOR  20141201   37.54   37.86  37.12    37.41   202300
689195      WOR  20141202   37.50   38.21  37.40    37.69   134700
689196      WOR  20141203   37.82   38.83  37.52    38.26   246100
689197      WOR  20141204   38.12   38.29  37.27    37.49   217000
689198      WOR  20141205   37.44   38.27  37.26    37.66   246600
689199      WOR  20141208   37.42   38.04  36.53    37.07   193100
689200      WOR  20141209   36.50   38.53  36.46    38.36   250100
689201      WOR  20141210   38.03   38.06  36.83    36.98   224600
689202      WOR  20141211   36.57   37.21  36.49    36.60   242300
689203      WOR  20141212   36.04   36.27  35.31    35.35   287900
689204      WOR  20141215   35.43   35.63  34.45    34.47   295900
689205      WOR  20141216   34.40   35.49  34.25    34.25   443200
689206      WOR  20141217   34.25   35.54  33.81    35.39   571200
689207      WOR  20141218   35.70   36.00  30.50    31.36  1611600
689208      WOR  20141219   30.98   31.19  30.06    30.06  1717100
689209      WOR  20141222   30.06   30.39  29.59    29.77   603200
689210      WOR  20141223   30.00   30.27  29.79    30.07   356100
689211      WOR  20141224   30.01   30.55  29.85    30.41   215000
689212      WOR  20141225   30.41   30.41  30.41    30.41        0
689213      WOR  20141226   30.66   30.76  30.38    30.43   210500
689214      WOR  20141229   30.53   31.30  30.45    30.89   381600
689215      WOR  20141230   30.86   31.18  30.50    30.86   476200
689216      WOR  20141231   31.05   31.09  30.09    30.09   520500

[10804 rows x 7 columns]>
----
(760191, 7)
(11700, 7)
<bound method NDFrame.head of        <ticker>    <date>  <open>  <high>  <low>  <close>    <vol>
0             A  20150101   40.94   40.94  40.94    40.94        0
1             A  20150102   41.18   41.31  40.37    40.56  1530700
2             A  20150105   40.32   40.46  39.70    39.80  2042200
3             A  20150106   39.81   40.02  39.02    39.18  2084500
4             A  20150107   39.52   39.81  39.29    39.70  3359600
5             A  20150108   40.24   40.98  40.18    40.89  2116300
6             A  20150109   41.00   41.00  40.29    40.59  1644900
7             A  20150112   40.61   40.72  39.95    40.11  2771100
8             A  20150113   40.47   40.70  39.33    39.55  2013400
9             A  20150114   39.03   39.10  38.21    39.06  5134000
10            A  20150115   39.33   39.41  37.99    38.01  2630200
11            A  20150116   37.86   38.46  37.76    38.25  3003900
12            A  20150119   38.25   38.25  38.25    38.25        0
13            A  20150120   38.43   38.66  37.76    37.93  5033600
14            A  20150121   37.75   38.41  37.68    38.16  2721600
15            A  20150122   38.51   39.86  38.12    39.65  4856500
16            A  20150123   39.60   39.60  38.76    38.81  1519200
17            A  20150126   38.79   39.17  38.47    39.15  1511200
18            A  20150127   38.70   39.25  38.58    38.75  1703500
19            A  20150128   39.01   39.05  37.96    38.00  2033500
20            A  20150129   38.00   38.47  37.69    38.46  2329900
21            A  20150130   38.01   38.32  37.71    37.77  3054300
22            A  20150202   37.90   38.76  37.71    38.69  2508400
23            A  20150203   39.04   39.63  38.92    39.62  2950300
24            A  20150204   39.33   39.46  38.82    39.11  2567400
25            A  20150205   39.22   39.82  39.22    39.53  1826300
26            A  20150206   39.54   39.81  39.23    39.34  2697200
27            A  20150209   39.23   39.43  38.95    39.04  3586100
28            A  20150210   39.31   39.76  38.78    39.67  1408700
29            A  20150211   39.64   39.81  39.23    39.33  3337000
...         ...       ...     ...     ...    ...      ...      ...
757812      ZBK  20151120   28.39   28.50  28.38    28.50     3100
757813      ZBK  20151123   28.51   28.58  28.35    28.58     7200
757814      ZBK  20151124   28.45   28.47  28.45    28.47      200
757815      ZBK  20151125   28.40   28.44  28.37    28.37     1200
757816      ZBK  20151126   28.37   28.37  28.37    28.37        0
757817      ZBK  20151127   28.13   28.15  27.98    27.98      700
757818      ZBK  20151130   28.28   28.28  28.28    28.28      100
757819      ZBK  20151201   28.13   28.32  28.08    28.32     1000
757820      ZBK  20151202   27.97   28.12  27.97    28.12     1000
757821      ZBK  20151203   28.04   28.04  27.95    27.96     3800
757822      ZBK  20151204   27.94   28.08  27.94    28.05      900
757823      ZBK  20151207   28.05   28.17  28.05    28.17     6700
757824      ZBK  20151208   28.22   28.22  28.05    28.05     1700
757825      ZBK  20151209   28.20   28.20  28.05    28.05     7400
757826      ZBK  20151210   28.15   28.15  28.12    28.12     1100
757827      ZBK  20151211   28.11   28.22  28.04    28.04     2200
757828      ZBK  20151214   28.04   28.04  27.79    27.91     9100
757829      ZBK  20151215   28.10   28.17  28.00    28.10     5100
757830      ZBK  20151216   28.17   28.19  28.00    28.19    15300
757831      ZBK  20151217   28.20   28.30  28.05    28.29     3300
757832      ZBK  20151218   28.13   28.41  28.13    28.41     8900
757833      ZBK  20151221   28.50   28.56  28.40    28.40     1600
757834      ZBK  20151222   28.42   28.48  28.42    28.48     1400
757835      ZBK  20151223   28.56   28.56  28.45    28.45      300
757836      ZBK  20151224   28.55   28.70  28.55    28.70    10000
757837      ZBK  20151225   28.70   28.70  28.70    28.70        0
757838      ZBK  20151228   28.52   28.63  28.52    28.63     1700
757839      ZBK  20151229   28.76   28.82  28.68    28.72     3100
757840      ZBK  20151230   28.83   28.83  28.73    28.73      400
757841      ZBK  20151231   28.85   28.85  28.76    28.76     2100

[11700 rows x 7 columns]>
----

(797710, 7)
(12350, 7)
<bound method NDFrame.head of        <ticker>    <date>  <open>  <high>  <low>  <close>    <vol>
3144        ABG  20160101   67.44   67.44  67.44    67.44        0
3145        ABG  20160104   66.17   67.34  65.74    66.52   219500
3146        ABG  20160105   66.66   67.06  64.29    65.13   264900
3147        ABG  20160106   63.82   63.82  56.99    57.34  1002600
3148        ABG  20160107   56.15   57.74  55.58    55.62   491400
3149        ABG  20160108   55.81   56.48  53.12    53.34   750500
3150        ABG  20160111   53.62   55.90  53.49    55.71   523500
3151        ABG  20160112   54.90   54.94  51.00    52.56   750800
3152        ABG  20160113   52.84   53.09  48.61    49.58   645700
3153        ABG  20160114   49.56   51.56  47.27    50.14   560300
3154        ABG  20160115   48.54   49.18  46.88    48.06   346400
3155        ABG  20160118   48.06   48.06  48.06    48.06        0
3156        ABG  20160119   48.46   49.06  44.81    45.97   484200
3157        ABG  20160120   45.47   49.00  44.81    48.19   493100
3158        ABG  20160121   48.50   49.53  47.20    47.36   376600
3159        ABG  20160122   48.27   49.09  47.59    47.97   347100
3160        ABG  20160125   49.58   50.94  48.72    49.33  1702600
3161        ABG  20160126   49.54   49.60  48.34    49.09  3361000
3162        ABG  20160127   48.81   49.45  46.47    46.94   820400
3163        ABG  20160128   47.28   47.73  44.62    45.81   658200
3164        ABG  20160129   46.00   47.08  45.57    47.08   630500
3165        ABG  20160201   46.48   47.14  45.54    46.75   349600
3166        ABG  20160202   45.90   46.34  44.13    45.07   550400
3167        ABG  20160203   45.56   45.98  43.56    45.20   609700
3168        ABG  20160204   47.83   50.48  46.19    48.63  1151700
3169        ABG  20160205   47.82   47.97  45.80    46.70  1073700
3170        ABG  20160208   45.96   48.20  45.48    46.07   896600
3171        ABG  20160209   45.45   49.08  45.38    47.02   966200
3172        ABG  20160210   47.18   49.67  47.08    48.96   825400
3173        ABG  20160211   47.96   50.07  47.83    49.10   738800
...         ...       ...     ...     ...    ...      ...      ...
782114      WRI  20161122   34.64   35.33  34.60    35.28   496500
782115      WRI  20161123   34.96   35.33  34.84    35.25   307500
782116      WRI  20161124   35.25   35.25  35.25    35.25        0
782117      WRI  20161125   35.34   35.71  35.21    35.37   189500
782118      WRI  20161128   35.33   35.82  35.13    35.31   483700
782119      WRI  20161129   35.36   35.72  35.31    35.70   733000
782120      WRI  20161130   35.33   35.73  35.24    35.51  1080000
782121      WRI  20161201   35.22   35.55  34.83    35.40  1083000
782122      WRI  20161202   35.61   35.96  35.08    35.40   973400
782123      WRI  20161205   35.35   35.82  35.35    35.60  1006000
782124      WRI  20161206   35.34   35.88  35.16    35.61   649200
782125      WRI  20161207   35.70   36.26  35.67    35.93   844100
782126      WRI  20161208   35.77   36.08  35.50    35.98   581500
782127      WRI  20161209   35.94   36.31  35.80    35.85   405700
782128      WRI  20161212   35.85   36.18  35.44    35.85  1298000
782129      WRI  20161213   35.94   36.11  35.30    35.77   931100
782130      WRI  20161214   35.83   35.83  34.82    34.83   562900
782131      WRI  20161215   34.72   35.25  34.33    34.45   513200
782132      WRI  20161216   34.82   35.44  34.80    35.10  1727200
782133      WRI  20161219   35.37   35.74  35.23    35.47   486600
782134      WRI  20161220   35.35   35.81  35.35    35.74   578600
782135      WRI  20161220   35.35   35.81  35.35    35.74   578600
782136      WRI  20161221   35.80   36.00  34.83    34.85   539500
782137      WRI  20161222   34.80   34.92  34.36    34.85   483100
782138      WRI  20161223   34.96   35.04  34.64    34.72   256800
782139      WRI  20161226   34.72   34.72  34.72    34.72        0
782140      WRI  20161227   34.76   34.92  34.63    34.74   294800
782141      WRI  20161228   34.68   34.73  34.43    34.69   556000
782142      WRI  20161229   34.71   35.28  34.67    35.23   477700
782143      WRI  20161230   35.24   36.11  35.24    35.79   728100

[12350 rows x 7 columns]>
----

In [ ]:
# OUTPUT 1st and last raw of each stock
writer = pd.ExcelWriter('Multiple_year_stock_closeStartEnd2.xlsx', engine='xlsxwriter')
for i in range(2012,2017,1):
    df=pd.read_excel('Multiple_year_stock_data.xlsx', sheetname=str(i))
    print(df.shape)
    
    #### 
    df = df[df['<vol>'] != 0]
    
    StockSet = set(df.sort_values('<ticker>')['<ticker>'].tolist())
    StockL=[]
    for Stock in StockSet:
        dfStock=df[df['<ticker>'] == Stock]
        dfStock=dfStock.iloc[[0, -1]]
        if dfStock.shape[0] > 1:
            dfStock.sort_values(['<ticker>', '<date>'], inplace=True)
            StockL.append(dfStock)
            
    
    df_concat=pd.concat(StockL)
    df_concat.sort_values(['<ticker>', '<date>'], inplace=True)
    print(df_concat.head())
    
    ####
    df_concat.to_excel(writer, index=False, sheet_name=str(i))

    print(df.shape)
    print(df_concat.shape)
    
    print('----')
    
writer.save()

In [56]:
# Import pandas
import pandas as pd

# Assign spreadsheet filename to `file`
file = 'Multiple_year_stock_closeStartEnd.xlsx'

# Load spreadsheet
xl = pd.ExcelFile(file)

# Print the sheet names
print(xl.sheet_names)

# Load a sheet into a DataFrame by name: df1
df1 = xl.parse('2012')

['2012', '2013', '2014', '2015', '2016']

In [47]:
df1.head(6)

  <ticker>    <date>  <open>  <high>  <low>  <close>     <vol>
0        A  20121231   39.64   40.97  39.64    40.94   3367500
1        A  20120103   35.83   36.99  35.74    36.48   2973000
2       AA  20120103   26.82   27.81  26.67    27.69  47114100
3       AA  20121231   25.56   26.07  25.44    26.04  19344200
4      AAN  20121231   27.59   28.32  27.45    28.28    290000
5      AAN  20120103   27.23   27.37  26.46    26.63    219800

In [46]:
df1.tail(6)

     <ticker>    <date>  <open>  <high>  <low>  <close>   <vol>
4648      ZNH  20120103   26.34   26.91  26.23    26.90   68900
4649      ZNH  20121231   25.10   25.85  25.10    25.85   30900
4650      ZTR  20121231   12.26   12.35  12.26    12.31  120400
4651      ZTR  20120103   12.24   12.36  12.16    12.28  543000
4652       ZX  20120103    3.22    3.22   3.03     3.11    7200
4653       ZX  20121231    2.91    3.13   2.90     2.99    6300

In [54]:
df1.sort_values(['<ticker>', '<date>'])

     <ticker>    <date>  <open>  <high>   <low>  <close>     <vol>
1           A  20120103   35.83   36.99   35.74    36.48   2973000
0           A  20121231   39.64   40.97   39.64    40.94   3367500
2          AA  20120103   26.82   27.81   26.67    27.69  47114100
3          AA  20121231   25.56   26.07   25.44    26.04  19344200
5         AAN  20120103   27.23   27.37   26.46    26.63    219800
4         AAN  20121231   27.59   28.32   27.45    28.28    290000
6         AAP  20120103   71.14   71.60   69.06    69.10    786500
7         AAP  20121231   71.39   72.55   71.30    72.35    455300
9         AAT  20120103   20.66   21.10   20.65    20.92    103600
8         AAT  20121231   27.22   27.97   27.10    27.93     80400
11        AAV  20120103    4.23    4.33    4.20     4.31    533700
10        AAV  20121231    3.15    3.24    3.14     3.24    290100
12         AB  20120103   13.33   13.54   13.31    13.45    418800
13         AB  20121231   17.38   17.67   17.21    17.43    232400
15        ABB  20120103   19.66   19.91   19.64    19.82   3126400
14        ABB  20121231   20.55   20.85   20.47    20.79   1549400
16        ABC  20120103   37.77   38.38   37.68    38.07   1937900
17        ABC  20121231   42.74   43.22   42.63    43.18   1295100
19        ABG  20120103   22.04   22.19   21.53    21.71    436800
18        ABG  20121231   30.65   32.24   30.65    32.03    349900
20        ABM  20120103   21.05   21.35   20.72    20.88    283500
21        ABM  20121231   19.64   19.98   19.55    19.95    185000
22        ABR  20120103    3.60    3.63    3.48     3.53     29600
23        ABR  20121231    5.98    6.13    5.95     5.99    279200
25        ABT  20120103   56.59   56.84   56.06    56.72   8489100
24        ABT  20121231   64.11   65.53   64.01    65.50   9125500
26        ABX  20120103   46.27   47.77   46.20    47.51   9011100
27        ABX  20121231   34.04   35.17   34.00    35.01   8321500
28        ACC  20120103   42.80   43.32   41.78    41.93    696600
29        ACC  20121231   45.76   46.15   45.64    46.13    531200
...       ...       ...     ...     ...     ...      ...       ...
4624      XRS  20120103   10.01   10.14    9.96     9.96     61900
4625      XRS  20121231    9.24    9.65    9.18     9.60    373200
4626      XRX  20120103    8.16    8.30    8.13     8.20  10334400
4627      XRX  20121231    6.66    6.84    6.62     6.82   8524100
4628      XYL  20120103   26.10   26.43   25.07    25.14   1059000
4629      XYL  20121231   26.36   27.11   26.34    27.10    536800
4630        Y  20120103  286.07  287.97  284.86   284.86     75000
4631        Y  20121231  331.99  336.58  328.13   335.42     70100
4633     YELP  20120302   22.05   26.00   22.00    24.58  17507600
4632     YELP  20121231   18.74   19.09   18.66    18.85    666500
4634      YGE  20120103   39.30   42.00   39.20    40.70   2450600
4635      YGE  20121231   22.70   24.00   22.60    23.50   1582700
4636      YPF  20120103   35.46   35.80   35.13    35.45    292500
4637      YPF  20121231   14.71   14.83   14.37    14.55    758100
4638      YUM  20120103   59.61   59.90   58.49    58.57   3404400
4639      YUM  20121231   64.72   66.47   64.56    66.40   3338600
4640      YZC  20120103   21.94   22.40   21.94    22.28    249900
4641      YZC  20121231   16.55   17.11   16.55    17.08    218100
4642     ZB-A  20120103   16.60   16.64   16.60    16.64      1200
4643     ZB-A  20121231   22.30   22.32   22.03    22.04      6200
4644     ZB-F  20120510   26.00   26.50   26.00    26.32     30000
4645     ZB-F  20121231   29.97   29.97   29.63    29.69       500
4647       ZF  20120103   11.84   11.92   11.84    11.92    205500
4646       ZF  20121231   12.05   12.19   12.04    12.16    101500
4648      ZNH  20120103   26.34   26.91   26.23    26.90     68900
4649      ZNH  20121231   25.10   25.85   25.10    25.85     30900
4651      ZTR  20120103   12.24   12.36   12.16    12.28    543000
4650      ZTR  20121231   12.26   12.35   12.26    12.31    120400
4652       ZX  20120103    3.22    3.22    3.03     3.11      7200
4653       ZX  20121231    2.91    3.13    2.90     2.99      6300

[4654 rows x 7 columns]